__title__       = "bookmark_manager"
__description__ = "Manage bookmarks for real."
__url__         = "https://github.com/vagrid/bookmark_manager"
__version__     = "0.0.1"
__author__      = "vagrid"
__license__     = "Apache 2.0"
__copyright__   = "Copyright 2022 vagrid"
